name: Download Music 下载音乐
description: Submit music download request 提交音乐下载请求
title: "Download Music 下载音乐"
labels: ["download"]
assignees: []

body:
  - type: dropdown
    id: type
    attributes:
      label: Download Type 下载类型
      description: Choose the content type to download 选择要下载的内容类型
      options:
        - Single Song 单曲
        - Album 专辑
    validations:
      required: true

  - type: input
    id: music_id
    attributes:
      label: Music ID 音乐ID
      description: Enter NetEase Cloud Music song ID or album ID 输入网易云音乐的歌曲ID或专辑ID
      placeholder: "Example 例如: 26619423"
    validations:
      required: true
      pattern: ^\d+$

  - type: checkboxes
    id: download_options
    attributes:
      label: Download Options 下载选项
      description: Choose what to download 选择要下载的内容
      options:
        - label: Lyrics only (no music file) 仅下载歌词（不下载音乐文件）
          required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Terms of Use 使用须知
      description: Please confirm the following 请确认以下内容
      options:
        - label: I confirm this is a legal download request for personal use only 我确认这是合法的下载请求，且仅用于个人用途
          required: true
