name: 下载音乐
description: 提交音乐下载请求
title: "下载音乐"
labels: ["download"]
assignees: []

body:
  - type: dropdown
    id: type
    attributes:
      label: 下载类型
      description: 选择要下载的内容类型
      options:
        - 单曲
        - 专辑
    validations:
      required: true

  - type: input
    id: music_id
    attributes:
      label: 音乐ID
      description: 输入网易云音乐的歌曲ID或专辑ID
      placeholder: "例如: 26619423"
    validations:
      required: true
      pattern: ^\d+$

  - type: checkboxes
    id: terms
    attributes:
      label: 使用须知
      description: 请确认以下内容
      options:
        - label: 我确认这是合法的下载请求，且仅用于个人用途
          required: true
