name: Cleanup Old Releases

on:
  schedule:
    - cron: '0 */3 * * *'  # 每3小时运行一次
  workflow_dispatch:        # 添加手动触发功能

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # 用于删除 releases

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Cleanup old releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node .github/scripts/cleanup-releases.js
