name: Download Music

on:
  issues:
    types: [opened]

jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # 用于创建 releases
      issues: write       # 用于更新 issues

    steps:
      - name: Initial Response
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '🤖 GitHub Action 已接收到您的请求，正在处理中...'
            });

      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Parse issue and download music
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node .github/scripts/process-issue.js
